dist: bionic

language: php

services:
  - mysql

git:
  depth: 1
  quiet: true

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.3
      env: WP_VERSION=latest WP_TRAVISCI=phpcs
    - php: 7.4
      env: WP_VERSION=latest
    - php: 8.0
      env: WP_VERSION=latest
    - php: 7.3
      env: WP_VERSION=trunk
  allow_failures:
    - php: 8.0
    - php: 7.3
      env: WP_VERSION=trunk

before_install:
  # Turn off Xdebug. See https://core.trac.wordpress.org/changeset/40138.
  - phpenv config-rm xdebug.ini || echo "Xdebug not available"

  - og_dir="$(pwd)"

  - export PATH="${HOME}/.config/composer/vendor/bin:${PATH}"
  - export WP_DEVELOP_DIR=/tmp/wordpress
  - export WP_CORE_DIR=/tmp/wordpress/

install:
  - composer validate --strict
  - bash bin/install-wp-tests.sh wordpress_unit_tests root '' localhost $WP_VERSION

  # Copy the wp-tests-config.php to the WP installation.
  - cp ${WP_TESTS_DIR-/tmp/wordpress-tests-lib}/wp-tests-config.php ${WP_CORE_DIR-/tmp/wordpress/}wp-tests-config.php

  # Set up the wp-content directory.
  - |
    cd $og_dir

    # Go into the core directory and replace wp-content.
    mkdir ${WP_CORE_DIR}wp-content/plugins/mantle-framework
    cp -R . "${WP_CORE_DIR}wp-content/plugins/mantle-framework"

  # Install Composer
  - |
    cd ${WP_CORE_DIR}wp-content/plugins/mantle-framework
    composer install
    pwd
    ls

script:
  - pwd
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer run phpcs
    fi
  - |
    composer run phpunit
