dist: bionic

sudo: false

language: php

services:
  - mysql

git:
  depth: 1
  quiet: true

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
  - main
  - develop

matrix:
  include:
    - php: 7.3
      env: WP_VERSION=latest WP_TRAVISCI=phpcs
  allow_failures:
    - php: 7.4
      env: WP_VERSION=latest

before_install:
  # Turn off Xdebug. See https://core.trac.wordpress.org/changeset/40138.
  - phpenv config-rm xdebug.ini || echo "Xdebug not available"

  - export PATH="${HOME}/.config/composer/vendor/bin:${PATH}"

  # Couple the PHPUnit version to the PHP version.
  - composer global require "phpunit/phpunit=6.1.*"

install:
  - composer validate --strict
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root "" 127.0.0.1 "$WP_VERSION"
      composer global require "phpunit/phpunit=6.1.*"
    fi
  - |
    composer install

script:
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer run phpcs
    fi
  - |
    which phpunit
    phpunit
