name: Coding Standards

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  coding-standards:
    uses: alleyinteractive/.github/.github/workflows/php-coding-standards.yml@main
    with:
      php: 8.1
  code-quality:
    uses: alleyinteractive/.github/.github/workflows/php-code-quality.yml@main
    with:
      command: "validate-monorepo"
      php: 8.1
