name: dependabot-auto-merge
on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    uses: alleyinteractive/.github/workflows/dependabot-auto-merge.yml@workflows
