name: Prepare a Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic Version without 'v' prefix"
        required: true
        type: "string"


jobs:
  provide_packages_json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
      - uses: "ramsey/composer-install@v1"
      - name: "Run Release Release"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: vendor/bin/monorepo-builder release v${{ inputs.version }}
