name: Split Monorepo

on:
  push:
    branches:
      - main
      - '*.*.x'
    tags:
      - 'v*.*.*'

jobs:
  provide_packages_json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # required for matrix of packages set
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - uses: "ramsey/composer-install@v2"

      # get package json list
      -
        id: output_data
        run: echo "matrix=$(vendor/bin/monorepo-builder packages-json)" >> $GITHUB_OUTPUT

    # this step is needed, so the output gets to the next defined job
    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split_monorepo:
    needs: provide_packages_json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v3

      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        # Uses an action in the root directory
        name: Monorepo Split of ${{ matrix.package }}
        uses: symplify/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'src/mantle/${{ matrix.package }}'
          repository_organization: 'mantle-framework'
          repository_name: '${{ matrix.package }}'
          repository_host: github.com
          user_name: "mantle-ci"
          user_email: "mantle@alley.com"
          branch: ${{ github.ref_name }}

      # with tag
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        id: extract-branch-name
        run: echo "branch=$(git branch -a --contains ${{ github.sha }} | grep -v 'HEAD' | sed -n 2p | awk '{ printf $1 }' | sed 's/remotes\/origin\///g')" >> $GITHUB_OUTPUT

      -
        if: "startsWith(github.ref, 'refs/tags/')"
        # Uses an action in the root directory
        name: Monorepo Tagged Split of ${{ matrix.package }}
        uses: symplify/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}

          package_directory: 'src/mantle/${{ matrix.package }}'
          repository_organization: 'mantle-framework'
          repository_name: '${{ matrix.package }}'
          repository_host: "github.com"
          user_name: "mantle-ci"
          user_email: "mantle@alley.com"
          branch: ${{ steps.extract-branch-name.outputs.branch }}
