name: Split Monorepo

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  provide_packages_json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # required for matrix of packages set
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - uses: "ramsey/composer-install@v1"

      # get package json list
      -
        id: output_data
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)"

    # this step is needed, so the output gets to the next defined job
    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split_monorepo:
    needs: provide_packages_json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v3

      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        # Uses an action in the root directory
        name: Monorepo Split of ${{ matrix.package }}
        uses: symplify/monorepo-split-github-action@2.2
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'src/mantle/${{ matrix.package }}'
          repository_organization: 'mantle-framework'
          repository_name: '${{ matrix.package }}'
          repository_host: github.com
          user_name: "mantle-ci"
          user_email: "mantle@alley.co"
          branch: "main"

      # with tag
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        # Uses an action in the root directory
        name: Monorepo Tagged Split of ${{ matrix.package }}
        uses: symplify/monorepo-split-github-action@2.2
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}

          package_directory: 'src/mantle/${{ matrix.package }}'
          repository_organization: 'mantle-framework'
          repository_name: '${{ matrix.package }}'
          repository_host: "github.com"
          user_name: "mantle-ci"
          user_email: "mantle@alley.co"
          branch: "main"
