name: Unit Tests

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:5.0
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    continue-on-error: ${{ matrix.can_fail }}
    strategy:
      fail-fast: true
      matrix:
        can_fail: [false]
        multisite: ["0", "1"]
        php: [7.4, 8.0]
        wp_version: ["latest"]

    name: Unit Test ${{ matrix.php }} @ ${{ matrix.wp_version }} (Multisite ${{ matrix.multisite }})

    env:
      CACHEDIR: /tmp
      WP_CORE_DIR: /tmp/wordpress
      WP_VERSION: ${{ matrix.wp_version }}
      WP_DB_HOST: 127.0.0.1
      WP_DB_USER: root
      WP_DB_PASSWORD: '""'
      WP_MULTISITE: ${{ matrix.multisite }}

    steps:
      - name: Cancel previous runs of this workflow (pull requests only)
        if: ${{ github.event_name == 'pull_request' }}
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Set up caching
        uses: actions/cache@v3.0.5
        env:
          cache-name: cache-composer-dependencies
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            /tmp/wordpress
            /tmp/wp-latest.json
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-invision/retry@v2.7.0
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install

      - name: Test Framework
        uses: nick-invision/retry@v2.7.0
        with:
          timeout_minutes: 2
          max_attempts: 3
          retry_on: error
          command: composer run phpunit
