name: Testing Suite

on:
  push:
    branches:
      - main
      - '*.*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  php-tests:
    strategy:
      fail-fast: false
      matrix:
        dependencies: ["lowest", "highest"]
        multisite: [true, false]
        os: [ubuntu-latest, windows-2019]
        php: [8.0, 8.1, 8.2]
        wordpress: ["latest"]
    uses: alleyinteractive/.github/.github/workflows/php-tests.yml@main
    name: "P${{ matrix.php }} - ${{ matrix.wordpress }} ${{ matrix.multisite && 'Multisite' || '' }} - ${{ matrix.dependencies }}"
    with:
      dependency-versions: ${{ matrix.dependencies }}
      multisite: ${{ matrix.multisite }}
      php: ${{ matrix.php }}
      os: ${{ matrix.os }}
      wordpress: ${{ matrix.wordpress }}
